import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import FooterComponent from "../components/footer-component";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kafui Alordo | Developer, Thinker, Doer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{ display: "flex", alignItems: "center" }}>
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              flexWrap: "wrap",
              maxWidth: "430px",
            }}
          >
            <div style={{ lineHeight: "0.501rem" }}>
              <h1>Kafui Alordo</h1>
              <p style={{ fontSize: "0.8rem" }}>
                Technnology Consulting and Software Engineering | Freelance
              </p>
            </div>

            {/* <div> */}
            <p style={{ fontSize: "1rem", color: "#887956" }}>
              I love design, and build impactful software applications based on
              best practieces, for individuals, coporate and organizations.
            </p>
            {/* </div> */}
          </div>
          {/* <div> */}
          <Image
            src="/static/kafui-alordo.jpg"
            alt="Vercel Logo"
            width={200}
            height={200}
            style={{ borderRadius: "100%" }}
          />
          {/* </div> */}
        </div>

        <div
          style={{
            display: "flex",
            flexDirection: "column",
            // alignItems: "center",
            // justifyContent: "center",
          }}
        >
          <div
            style={{
              display: "flex",
              alignItems: "center",
              maxWidth: "240px",
              justifyContent: "center",
            }}
          >
            <h4>thoughts</h4>
          </div>

          <div className={styles.grid}>
            <a href="https://nextjs.org/docs" className={styles.card}>
              <h2>Documentation &rarr;</h2>
              <p>Find in-depth information about Next.js features and API.</p>
            </a>

            <a href="https://nextjs.org/learn" className={styles.card}>
              <h2>Learn &rarr;</h2>
              <p>Learn about Next.js in an interactive course with quizzes!</p>
            </a>

            <a
              href="https://github.com/vercel/next.js/tree/canary/examples"
              className={styles.card}
            >
              <h2>Examples &rarr;</h2>
              <p>Discover and deploy boilerplate example Next.js projects.</p>
            </a>

            <a
              href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              className={styles.card}
            >
              <h2>Deploy &rarr;</h2>
              <p>
                Instantly deploy your Next.js site to a public URL with Vercel.
              </p>
            </a>
          </div>
        </div>
      </main>

      <FooterComponent />
    </div>
  );
};

export default Home;
